<?php

/**
 * @file
 * Private message messenger NodeJS.
 */

use Drupal\Core\Url;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\image\Entity\ImageStyle;
use Drupal\Component\Utility\Unicode;

/**
 * Implements hook_nodejs_handlers_info().
 */
function private_message_messenger_nodejs_nodejs_handlers_info() {
  return ['private_message_messenger_nodejs/handler'];
}

/**
 * Implements hook_entity_update().
 */
function private_message_messenger_nodejs_entity_update(EntityInterface $entity) {
  if ($entity->getEntityTypeId() == 'private_message_thread') {
    foreach ($entity->getMembers() as $member) {
      private_message_messenger_nodejs_thread_updated_notify($member->id(), $entity);
    }
  }
}

/**
 * Notify a user of an updated thread.
 *
 * @param int $uid
 *   User id.
 * @param Drupal\Core\Entity\EntityInterface|Drupal\private_message\Entity\PrivateMessageThreadInterface $thread
 *   The thread entity.
 */
function private_message_messenger_nodejs_thread_updated_notify($uid, EntityInterface $thread) {
  // Get last message details.
  $latest_messages = array_reverse($thread->getMessages());
  $last_message = reset($latest_messages);
  $owner = $last_message->getOwner();
  $you = (int) \Drupal::currentUser()->id();
  $config = \Drupal::config('private_message_messenger_nodejs.settings');

  // Build notification.
  $notification = [
    '#theme' => 'pmmn_notification',
    '#body' => $last_message->getMessage(),
    '#owner' => $owner,
    '#thread' => $thread,
  ];

  // Get parsed data based on notification template.
  $data = [];
  foreach ($notification as $key => $val) {
    $data[ltrim($key, '#')] = $val;
  }
  _private_message_messenger_nodejs_parse_notification($data);

  // Notify that thread is updated.
  $message = (object) [
    'data' => (object) [
      'ownerName' => $owner->getDisplayName(),
      'ownerId' => $owner->id(),
      'threadId' => $thread->id(),
      'isYou' => ((int) $uid === $you),
      'notifyType' => $config->get('notification_type'),
      'notifyTime' => (int) $config->get('notification_time'),
      'body' => render($notification),
      'snippet' => $data['snippet'],
      'image' => $data['image'],
      'url' => $data['url'],
    ],
    'channel' => 'nodejs_user_' . $uid,
    'callback' => 'pmnThreadUpdated',
  ];

  nodejs_get_nodejs()->enqueueMessage($message);
}

/**
 * Implements hook_theme().
 */
function private_message_messenger_nodejs_theme($existing, $type, $theme, $path) {
  return [
    'pmmn_notification' => [
      'variables' => [
        'title' => NULL,
        'body' => NULL,
        'snippet' => NULL,
        'owner' => NULL,
        'thread' => NULL,
        'image' => NULL,
        'thread_id' => NULL,
        'url' => NULL,
      ],
    ],
  ];
}

/**
 * Parse the variables for a private message notification.
 *
 * @param array $variables
 *   Array containing: owner, body, thread.
 */
function _private_message_messenger_nodejs_parse_notification(array &$variables) {
  $config = \Drupal::config('private_message_messenger.settings');
  $user = $variables['owner'];

  // If the user has a profile image.
  $variables['image'] = '';
  if ($user->hasField('user_picture') && $image = $user->get('user_picture')->first()) {
    $image_uri = $image->entity->getFileUri();

    if ($image_uri) {
      $style = $config->get('image_style');
      $style = !empty($style) ? $style : 'thumbnail';
      $variables['image'] = ImageStyle::load($style)->buildUrl($image_uri);
    }
  }

  // Set the title to be the username.
  $variables['title'] = $user->getDisplayName();

  // Add trimmed snippet.
  $variables['snippet'] = Unicode::truncate($variables['body'], 60, FALSE, TRUE);

  // Link to the messenger thread.
  $variables['url'] = Url::fromUserInput('/messenger#thread-' . $variables['thread']->id())->setAbsolute()->toString();
}

/**
 * Implements hook_preprocess_pmn_notification().
 */
function template_preprocess_pmmn_notification(&$variables) {
  _private_message_messenger_nodejs_parse_notification($variables);
}
